project:
  type: website

website:
  title: "Investment Notes"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Macro
        href: macro/index.qmd
      - text: Stocks
        href: stocks/index.qmd
      - text: Daily
        href: daily/index.qmd
      - text: YouTube
        href: youtube/index.qmd

execute:
  freeze: auto

jupyter:
  kernelspec:
    name: python3
    language: python
    display_name: Python 3

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
